"use client"
/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/OwCPKTNXatz
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

import {
    Card,
    CardHeader,
    CardTitle,
    CardDescription,
    CardContent,
    CardFooter,
  } from "@/components/ui/card";
  import { Label } from "@/components/ui/label";
  import { Input } from "@/components/ui/input";
  import {
    Select,
    SelectTrigger,
    SelectValue,
    SelectContent,
    SelectItem,
  } from "@/components/ui/select";
  import { Button } from "@/components/ui/button";
    import { useEffect, useState } from "react";
import { useParams } from "next/navigation";
    
  type MedicalSupply = {
    id: number;
    quantity: number;
    description: string;
    category: string;
    inStock: boolean;
  };
  
  const medicalSupplies = [
    {
      id: 1,
      quantity: 50,
      description: "Mascarillas quirúrgicas",
      category: "Equipos de protección",
      inStock: true,
    },
    {
      id: 2,
      quantity: 20,
      description: "Guantes de látex",
      category: "Equipos de protección",
      inStock: true,
    },
    {
      id: 3,
      quantity: 5,
      description: "Termómetros digitales",
      category: "Instrumentos médicos",
      inStock: false,
    },
    {
      id: 4,
      quantity: 100,
      description: "Vendas elásticas",
      category: "Suministros médicos",
      inStock: true,
    },
    {
      id: 5,
      quantity: 15,
      description: "Jeringas desechables",
      category: "Suministros médicos",
      inStock: true,
    },
    {
      id: 6,
      quantity: 30,
      description: "Alcohol isopropílico",
      category: "Suministros médicos",
      inStock: false,
    },
    {
      id: 7,
      quantity: 80,
      description: "Gasas estériles",
      category: "Suministros médicos",
      inStock: true,
    },
    {
      id: 8,
      quantity: 10,
      description: "Estetoscopios",
      category: "Instrumentos médicos",
      inStock: true,
    },
    {
      id: 9,
      quantity: 25,
      description: "Batas quirúrgicas",
      category: "Equipos de protección",
      inStock: true,
    },
    {
      id: 10,
      quantity: 40,
      description: "Apósitos adhesivos",
      category: "Suministros médicos",
      inStock: true,
    },
  ];

export default function page() {

      const [supply, setSupply] = useState<MedicalSupply | null>(null);
      const { id } = useParams();
      useEffect(() => {
        // Buscar el supply por ID
        const foundSupply = medicalSupplies.find((s) => s.id === Number(id));
        if (foundSupply) {
          setSupply(foundSupply);
        } else {

        }
      }, []);
    
      if (!supply) {
        return <div>Cargando...</div>;
      }

    return (
        <Card className=" m-auto w-full max-w-[600px]">
            <CardContent className="py-6 xl:py-8 gap-3 flex flex-col">
              <div className="flex flex-col gap-4">
                <div className="flex flex-col gap-1 xl:gap-2">
                  <Label htmlFor="firstName">Descripcción</Label>
                  <Input id="firstName" placeholder="Descripcción" value={supply.description} />
                </div>
                <div className="flex flex-col gap-1 xl:gap-2">
                  <Label htmlFor="lastName">Categoria</Label>
                  <Input id="lastName" placeholder="Categoria" value={supply.category} />
                </div>
              </div>
              <div className="flex flex-col gap-1 xl:gap-2">
                <Label htmlFor="username">Cantidad</Label>
                <Input id="username" placeholder="cantidad" value={supply.quantity}/>
              </div>
            </CardContent>
            <CardFooter className="flex justify-end">
              <Button type="submit">Guardar</Button>
            </CardFooter>
          </Card>
    );
}
