version: '3.5'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: next-prod
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
    restart: always
