/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/TRWPIIvFGfr
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
"use client";
import { Card, CardHeader, CardTitle, CardDescription, CardContent, CardFooter } from "@/components/ui/card"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Checkbox } from "@/components/ui/checkbox"
import { Button } from "@/components/ui/button"
import { useState } from "react"

export function MedicineTable() {
  const [formData, setFormData] = useState({
    id: "",
    tracer: false,
    code: "",
    name: "",
    category: "",
    realDemandAverage: "",
    physicalStock: "",
    availableStock: "",
    position: "",
  })
  const handleSubmit = (e: { preventDefault: () => void }) => {
    e.preventDefault()
    if (
      !formData.id ||
      !formData.code ||
      !formData.name ||
      !formData.category ||
      !formData.realDemandAverage ||
      !formData.physicalStock ||
      !formData.availableStock ||
      !formData.position
    ) {
      alert("Please fill in all fields before saving.")
      return
    }
    console.log("Saving form data:", formData)
  }
  return (
    <Card className="w-full max-w-3xl">
      <CardHeader>
        <CardTitle>Medicamentos del Centro de Salud</CardTitle>
        <CardDescription>Ingrese la información de los medicamentos</CardDescription>
      </CardHeader>
      <CardContent className="grid gap-6">
        <div className="grid grid-cols-2 gap-4">
          <div className="grid gap-2">
            <Label htmlFor="id">ID</Label>
            <Input id="id" type="number" placeholder="Ingrese el ID" />
          </div>
          <div className="grid gap-2">
            <Label htmlFor="tracer">Trazador</Label>
            <Checkbox id="tracer" />
          </div>
        </div>
        <div className="grid grid-cols-2 gap-4">
          <div className="grid gap-2">
            <Label htmlFor="code">Código</Label>
            <Input id="code" placeholder="Ingrese el código" />
          </div>
          <div className="grid gap-2">
            <Label htmlFor="name">Nombre</Label>
            <Input id="name" placeholder="Ingrese el nombre" />
          </div>
        </div>
        <div className="grid grid-cols-2 gap-4">
          <div className="grid gap-2">
            <Label htmlFor="category">Categoría</Label>
            <Input id="category" placeholder="Ingrese la categoría" />
          </div>
          <div className="grid gap-2">
            <Label htmlFor="real-demand-average">Promedio de demanda real</Label>
            <Input id="real-demand-average" type="number" placeholder="Ingrese el promedio" />
          </div>
        </div>
        <div className="grid grid-cols-2 gap-4">
          <div className="grid gap-2">
            <Label htmlFor="physical-stock">Existencia física</Label>
            <Input id="physical-stock" type="number" placeholder="Ingrese la existencia física" />
          </div>
          <div className="grid gap-2">
            <Label htmlFor="available-stock">Existencia disponible</Label>
            <Input id="available-stock" type="number" step="0.01" placeholder="Ingrese la existencia disponible" />
          </div>
        </div>
        <div className="grid gap-2">
          <Label htmlFor="position">Puesto</Label>
          <Input id="position" placeholder="Ingrese el puesto" />
        </div>
      </CardContent>
      <CardFooter>
        <Button type="submit" className="ml-auto">
          Guardar
        </Button>
      </CardFooter>
    </Card>
  )
}
